### ISSUE TITLE
"Error: DarkIronSword is not a valid Weapon Name" But shows Viridescent in GO upload

### ISSUE THREAD

**Issue by Sinesthesia** [Andrewthe13th/Genshin_Scanner#4]
This was the only issue I had when first trying this one out.
![image](https://user-images.githubusercontent.com/23565001/134706498-31691acf-c724-4741-a890-23026b74cea0.png)
![image](https://user-images.githubusercontent.com/23565001/134706627-c61ed01e-4c14-42d0-9b43-40302a6e9293.png)

**Comment by Andrewthe13th** [comment]
So yea i have no entry for DarkIronSword. And my GOOD format converter needs to be correct to "TheViridescentHunt". Thanks for reporting.

**Comment by southrop** [comment]
Scanning for the Dark Iron Sword works fine now, but when adding it to GO, it produces an error because the key is case sensitive. GO expects `DarkIronSword` but the scanner produces an entry with the key `darkironsword`.

![image](https://user-images.githubusercontent.com/2568167/135734215-19213b8b-1adc-457d-b610-9b3f7bcb41e6.png)

**Comment by Andrewthe13th** [comment]
Thanks for reporting. Sorry for the mistake. Forgot to upper case
![image](https://user-images.githubusercontent.com/11446437/135734297-aae8fd2d-cde8-401a-a16f-5e645a314a1d.png)
