### ISSUE TITLE
Tessdata is not included in the repository

### ISSUE THREAD

**Issue by doxxx** [Andrewthe13th/Genshin_Scanner#45]
The tessdata folder is not included in the repository. It appears to be only included in the release zips, which means I cannot use the program if I compile it myself -- it crashes after I start scanning.

Additionally, Windows Defender thinks the release zip contains a virus and deletes the file as soon as it's finished downloading. I had to download it using wget under WSL to discover that the tessdata folder is included in the zip.

**Comment by Andrewthe13th** [comment]
Yea i need to figure out to add the tessdata folder. Also windows defender always thinks this program is a virus. Not sure if i can submit the entire project to Microsoft for verification. I have only sent them the release program so Microsoft doesn't flag it as a virus. In order to add the tess file currently create a bin folder. 
![image](https://user-images.githubusercontent.com/11446437/140446158-836605ce-a87d-4de1-a87c-0c048234f4d0.png)
Then a Debug folder. Place the tessdata from the release into the the Debug folder.

**Comment by Andrewthe13th** [comment]
I will try to make this better in the future i just can't do it right now as I made quite a bit of changes in this new version coming up.I also need to expand on the read me file more for developers and for users. Let me know if you need anymore help.

**Comment by doxxx** [comment]
How is the tessdata folder generated? Some kind of training process? Or is it a prebuilt model from Tesseract?

**Comment by Andrewthe13th** [comment]
yea training process. I trained these files.

**Comment by hastarin** [comment]
> Yea i need to figure out to add the tessdata folder.

Going purely from memory, so may not be exact but you should be able to add it to the project and set it's type in properties to Content and Copy if Newer.
